# Generated by Django 3.1.5 on 2021-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0003_auto_20210120_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
