# Generated by Django 3.1.5 on 2021-01-21 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0004_appusers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsmodel',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
