# Generated by Django 3.1.5 on 2021-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0006_appusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
