# Generated by Django 3.1.5 on 2021-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0007_auto_20210123_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appusers',
            name='hoby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appusers',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
