# Generated by Django 3.1.5 on 2021-01-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0008_auto_20210124_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='introduction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
