# Generated by Django 3.1.5 on 2021-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0009_appusers_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='shonin_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
