# Generated by Django 3.2 on 2021-04-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNSapp', '0011_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='sns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SNSapp.snsmodel'),
        ),
    ]
